name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Build EXE
        run: npm run packageExe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/*.exe
